name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Run tests
        run: |
          docker build -t basher113/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true basher113/react-test npm test

      - name: Build images
        run: |
          docker build -t basher113/complex-client ./client
          docker build -t basher113/complex-server ./server
          docker build -t basher113/complex-nginx ./nginx
          docker build -t basher113/complex-worker ./worker

      - name: Push images
        run: |
          docker push basher113/complex-client
          docker push basher113/complex-server
          docker push basher113/complex-nginx
          docker push basher113/complex-worker
